const D=window.RICARDO_DATA,G=window.RICARDO_GLOSSES||{};const byId=id=>document.getElementById(id);const saved=new Set(JSON.parse(localStorage.getItem("ricardoSaved")||"[]"));let player=null,stopTimer=null,stopMonitor=null,activeEnd=null,currentQuiz=0,quizScore=0,locked=false,speechFallback=null,activeSpeechLesson=null;
function sourceFor(l){return D.sources.find(s=>s.id===l.source)}function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function wordTokens(text){const matches=[...text.matchAll(/[\p{L}\p{M}]+(?:['’][\p{L}\p{M}]+)*/gu)];return matches.map((m,i)=>{const previousEnd=i?matches[i-1].index+matches[i-1][0].length:0,next=matches[i+1]?.index??text.length;const opening=(text.slice(previousEnd,m.index).match(/[¿¡]+\s*$/)||[""])[0].trim();const punctuation=text.slice(m.index+m[0].length,next).replace(/[¿¡]+\s*$/,"").trim();const key=m[0].toLocaleLowerCase("es");return{word:opening+m[0]+punctuation,plain:m[0],gloss:G[key]||"意味を確認",start:m.index,end:m.index+m[0].length}})}
function karaokeMarkup(l){return wordTokens(l.spanish).map((t,i)=>`<span class="karaoke-word" data-word-index="${i}" data-char-start="${t.start}" data-char-end="${t.end}"><span class="word-es">${esc(t.word)}</span><span class="word-ja">${esc(t.gloss)}</span></span>`).join("")}
function karaokeLines(id){return [...document.querySelectorAll(`.karaoke-line[data-lesson-id="${id}"]`)]}
function clearSpeechUI(){clearInterval(speechFallback);speechFallback=null;document.querySelectorAll(".karaoke-line.is-speaking").forEach(x=>x.classList.remove("is-speaking"));document.querySelectorAll(".karaoke-word.is-current").forEach(x=>{x.classList.remove("is-current");x.removeAttribute("aria-current")});document.querySelectorAll(".clear-btn.is-playing,.study-controls .clear.is-playing").forEach(x=>{x.classList.remove("is-playing");x.textContent=x.dataset.idleLabel||"▶ クリア"});activeSpeechLesson=null}
function highlightWord(id,index){karaokeLines(id).forEach(line=>{line.classList.add("is-speaking");line.querySelectorAll(".karaoke-word").forEach((word,i)=>{word.classList.toggle("is-current",i===index);if(i===index)word.setAttribute("aria-current","true");else word.removeAttribute("aria-current")})})}
function wordAtCharacter(tokens,charIndex){const exact=tokens.findIndex(t=>charIndex>=t.start&&charIndex<t.end);if(exact>=0)return exact;for(let i=tokens.length-1;i>=0;i--)if(charIndex>=tokens[i].start)return i;return 0}
function nav(view){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("is-active",v.id===view));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("is-active",b.dataset.view===view));history.replaceState(null,"",`#${view}`);scrollTo(0,0)}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>nav(b.dataset.view));document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>nav(b.dataset.jump));
function lessonCard(l,i){const t=byId("lesson-card-template").content.cloneNode(true);t.querySelector(".lesson-number").textContent=String(i+1).padStart(2,"0");t.querySelector(".confidence").textContent=l.confidence==="high"?"HIGH CONFIDENCE":"NORMALIZED";const line=t.querySelector(".lesson-spanish");line.dataset.lessonId=l.id;line.setAttribute("aria-label",l.spanish);line.innerHTML=karaokeMarkup(l);t.querySelector(".lesson-japanese").textContent=l.japanese;t.querySelector(".listen-btn").onclick=()=>playLesson(l);const clear=t.querySelector(".clear-btn");clear.dataset.clearId=l.id;clear.dataset.idleLabel="▶ クリア";clear.onclick=()=>speakClear(l);const save=t.querySelector(".save-btn");save.textContent=saved.has(l.id)?"✓ 覚えた":"＋ 覚える";save.classList.toggle("is-saved",saved.has(l.id));save.onclick=()=>toggleSaved(l.id,save);return t}
function toggleSaved(id,button){saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem("ricardoSaved",JSON.stringify([...saved]));button.textContent=saved.has(id)?"✓ 覚えた":"＋ 覚える";button.classList.toggle("is-saved",saved.has(id));updateStats()}
function renderFeatured(){const box=byId("featured-lessons");box.innerHTML="";[D.lessons[10],D.lessons[6],D.lessons[8]].forEach((l,i)=>box.append(lessonCard(l,i)))}
function renderStudy(filter="all"){const box=byId("study-list");box.innerHTML="";D.lessons.filter(l=>filter==="all"||l.tags.includes(filter)).forEach((l,i)=>{const a=document.createElement("article");a.className="study-item";a.innerHTML=`<div class="study-index">${String(i+1).padStart(2,"0")}</div><div class="study-main"><h2 class="karaoke-line" data-lesson-id="${l.id}" aria-label="${esc(l.spanish)}">${karaokeMarkup(l)}</h2><p class="ja"><span>文全体</span>${esc(l.japanese)}</p><div class="study-detail"><div><h4>STRUCTURE</h4><p>${esc(l.literal)}</p></div><div><h4>KEY WORDS</h4><div class="tokens">${l.vocab.map(v=>`<span class="token">${esc(v)}</span>`).join("")}</div><p style="margin-top:12px;font-size:12px;color:#777">${esc(sourceFor(l).title)} · ${fmt(l.start)}–${fmt(l.end)}</p></div></div></div><div class="study-controls"><button class="play clear" data-clear-id="${l.id}" data-idle-label="▶ クリア" aria-label="クリア音声">▶ クリア</button><button class="play original" aria-label="本人の音声">本人</button><button class="expand" aria-label="解説を開く">＋</button></div>`;a.querySelector(".original").onclick=()=>playLesson(l);a.querySelector(".clear").onclick=()=>speakClear(l);a.querySelector(".expand").onclick=e=>{a.classList.toggle("is-open");e.currentTarget.textContent=a.classList.contains("is-open")?"−":"＋"};box.append(a)})}
document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("is-active"));b.classList.add("is-active");renderStudy(b.dataset.filter)});
function renderWords(){byId("word-cloud").innerHTML=D.words.map(w=>`<button class="cloud-word" data-word="${esc(w.word)}" data-size="${w.count>=5?3:w.count>=3?2:1}">${esc(w.word)}</button>`).join("");byId("word-list").innerHTML=D.words.map(w=>`<article class="word-row" id="word-${w.word.replace(/\s/g,"-")}"><header><h3>${esc(w.word)}</h3><span class="count">CORPUS × ${w.count}</span></header><p>${esc(w.meaning)}</p><div class="example">${esc(w.example)}</div></article>`).join("");document.querySelectorAll(".cloud-word").forEach(b=>b.onclick=()=>byId(`word-${b.dataset.word.replace(/\s/g,"-")}`).scrollIntoView({behavior:"smooth",block:"center"}))}
function fmt(sec){return `${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,"0")}`}
function stopAllAudio(){clearTimeout(stopTimer);clearInterval(stopMonitor);activeEnd=null;if(player?.pauseVideo)player.pauseVideo();const clip=byId("clip-player");clip.pause();clip.currentTime=0;if("speechSynthesis" in window)speechSynthesis.cancel();clearSpeechUI()}
function armSegmentStop(end){activeEnd=end;clearInterval(stopMonitor);stopMonitor=setInterval(()=>{if(!player?.getCurrentTime||activeEnd===null)return;if(player.getCurrentTime()>=activeEnd-.12){player.pauseVideo();clearInterval(stopMonitor);activeEnd=null}},100);clearTimeout(stopTimer);stopTimer=setTimeout(()=>{if(activeEnd!==null){player.pauseVideo();clearInterval(stopMonitor);activeEnd=null}},Math.max(12000,(end-(player?.getCurrentTime?.()||end-10)+8)*1000))}
window.onYouTubeIframeAPIReady=()=>{player=new YT.Player("yt-player",{height:"124",width:"220",videoId:D.sources[0].youtubeId,playerVars:{playsinline:1,controls:1,rel:0,origin:location.origin},events:{onStateChange:e=>{if(e.data===YT.PlayerState.PLAYING&&activeEnd!==null)armSegmentStop(activeEnd)}}})};
function playLesson(l){const s=sourceFor(l);stopAllAudio();byId("player-dock").classList.add("is-open");byId("dock-title").textContent=l.spanish;byId("dock-time").textContent=`本人 · ${s.title} · ${fmt(l.start)}–${fmt(l.end)}`;const clip=byId("clip-player"),frame=byId("yt-player");if(l.audioClip){frame.style.display="none";clip.style.display="block";clip.src=l.audioClip;clip.play();return}clip.style.display="none";frame.style.display="block";const go=()=>{activeEnd=l.end;player.loadVideoById({videoId:s.youtubeId,startSeconds:l.start,endSeconds:l.end});armSegmentStop(l.end)};player&&player.loadVideoById?go():setTimeout(go,700)}
function speakClear(l){stopAllAudio();if(!("speechSynthesis" in window)){alert("このブラウザは読み上げ音声に対応していません。");return}const tokens=wordTokens(l.spanish),u=new SpeechSynthesisUtterance(l.spanish);u.lang="es-ES";u.rate=.82;u.pitch=1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/^es(-|_)/i.test(v.lang)&&/(Google|Microsoft|Mónica|Monica|Jorge|Paulina|Premium|Enhanced)/i.test(v.name))||voices.find(v=>/^es(-|_)/i.test(v.lang))||null;activeSpeechLesson=l.id;document.querySelectorAll(`[data-clear-id="${l.id}"]`).forEach(x=>{x.classList.add("is-playing");x.textContent="■ 再生中"});byId("player-dock").classList.add("is-open");byId("dock-title").textContent=l.spanish;byId("dock-time").textContent="クリア音声 · 単語と日本語を同期中";let boundarySeen=false,started=performance.now();const fallbackDuration=Math.max(1600,tokens.length*430/u.rate);highlightWord(l.id,0);u.onstart=()=>{started=performance.now();speechFallback=setInterval(()=>{if(boundarySeen||activeSpeechLesson!==l.id)return;const progress=Math.min(.999,(performance.now()-started)/fallbackDuration);highlightWord(l.id,Math.min(tokens.length-1,Math.floor(progress*tokens.length)))},90)};u.onboundary=e=>{if(activeSpeechLesson!==l.id)return;boundarySeen=true;highlightWord(l.id,wordAtCharacter(tokens,e.charIndex||0))};const finish=()=>{if(activeSpeechLesson!==l.id)return;clearSpeechUI();setTimeout(()=>byId("player-dock").classList.remove("is-open"),350)};u.onend=finish;u.onerror=finish;speechSynthesis.speak(u)}
byId("dock-close").onclick=()=>{byId("player-dock").classList.remove("is-open");stopAllAudio()};
const quizLessons=[D.lessons[10],D.lessons[6],D.lessons[8],D.lessons[2],D.lessons[9]];const wrongMeanings=["選手交代を急ぐ必要がある。","守備だけに集中しなければならない。","この試合は簡単だった。","個人の能力がすべてだ。","結果よりも内容は重要ではない。","来季は違うクラブへ行きたい。"];
function renderQuiz(){locked=false;const l=quizLessons[currentQuiz%quizLessons.length];const options=[l.japanese,...wrongMeanings.slice(currentQuiz,currentQuiz+2)].sort(()=>Math.random()-.5);byId("quiz-shell").innerHTML=`<div class="quiz-kicker">QUESTION ${currentQuiz+1} / ${quizLessons.length}</div><div class="quiz-progress"><span style="width:${(currentQuiz/quizLessons.length)*100}%"></span></div><button class="quiz-audio" aria-label="音声を聞く">▶</button><h2>リカルドは何と言っていますか？</h2><div class="quiz-options">${options.map(o=>`<button class="quiz-option">${esc(o)}</button>`).join("")}</div><div class="quiz-feedback"></div><button class="quiz-next">次へ →</button>`;byId("quiz-shell").querySelector(".quiz-audio").onclick=()=>playLesson(l);byId("quiz-shell").querySelectorAll(".quiz-option").forEach(b=>b.onclick=()=>{if(locked)return;locked=true;const ok=b.textContent===l.japanese;b.classList.add(ok?"correct":"wrong");if(ok)quizScore++;else [...byId("quiz-shell").querySelectorAll(".quiz-option")].find(x=>x.textContent===l.japanese)?.classList.add("correct");byId("quiz-shell").querySelector(".quiz-feedback").innerHTML=`<b>${ok?"正解。":"もう一度聞いてみよう。"}</b><br><span>${esc(l.spanish)}</span>`;byId("quiz-shell").querySelector(".quiz-next").classList.add("show")});byId("quiz-shell").querySelector(".quiz-next").onclick=()=>{currentQuiz++;currentQuiz>=quizLessons.length?renderQuizResult():renderQuiz()}}
function renderQuizResult(){byId("quiz-shell").innerHTML=`<div class="quiz-kicker">FULL TIME</div><h2 style="font-size:58px">${quizScore} / ${quizLessons.length}</h2><p>実際の音声から意味を選べました。間違えた文は「学ぶ」で構造を確認できます。</p><button class="quiz-next show">もう一度 →</button>`;byId("quiz-shell").querySelector("button").onclick=()=>{currentQuiz=0;quizScore=0;renderQuiz()}}
function renderSources(){byId("source-list").innerHTML=D.sources.map(s=>`<article class="source-card"><img src="https://i.ytimg.com/vi/${s.youtubeId}/hqdefault.jpg" alt="${esc(s.title)} thumbnail"><div><h3>${esc(s.title)}</h3><p>${esc(s.date)} · ${esc(s.channel)} · ${fmt(s.duration)}</p><p>${esc(s.method)}</p></div><a href="${s.url}" target="_blank" rel="noopener">元動画 ↗</a></article>`).join("");byId("deleted-ledger").innerHTML=D.deleted.map(d=>`<div class="deleted-item"><b>${d[0]}</b><small>${d[1]}</small></div>`).join("")}
function updateStats(){byId("stat-lessons").textContent=D.lessons.length;byId("stat-words").textContent=D.words.length;byId("stat-sources").textContent=D.sources.length;byId("progress-ring").textContent=`${Math.round(saved.size/D.lessons.length*100)}%`}
renderFeatured();renderStudy();renderWords();renderQuiz();renderSources();updateStats();const initial=location.hash.slice(1);if(["home","study","words","quiz","sources"].includes(initial))nav(initial);if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});
